### ISSUE TITLE
Character - Implement mobile input

### ISSUE THREAD

**Issue by bjarnur** [elBjarnacho/KingOfTheCube#15]
To begin with we can implement this without AR functionality. Therefore this ticket implies making sure the camera makes sense when playing on mobile without AR.

**Comment by bjarnur** [comment]
@NoNiMad We can close this one right? :) For future features implementing the AR controls will be done when the feature is introduced.

**Comment by NoNiMad** [comment]
Moving and jumping are working and if we want to work on more complex gestures it should have it's own ticket/issue. Closing streak!
