### ISSUE TITLE
Add modular elements to the voxel, remove current ones

### ISSUE THREAD

**Issue by pooryag** [elBjarnacho/KingOfTheCube#20]

**Comment by bjarnur** [comment]
@pooryag - Cube looks great, nice work! One issue regarding the Platform and Ladder meshes, if you put translate them to 0,0,0 they don't appear there.. seems like their internal location is off in some way. Do you know if this is something we could fix? 

Edit: Reason I'm wondering is that it's easier to systematically place objects if they all start at 0,0,0.

**Comment by bjarnur** [comment]
Can this one be closed?  :)

**Comment by pooryag** [comment]
Weird! I will check it tonight!

**Comment by bjarnur** [comment]
Closed because a separate ticket has been created for fixing remaining bugs: https://github.com/elBjarnacho/KingOfTheCube/issues/27
