### ISSUE TITLE
Character - Implement throwing objects (rocks, bombs)

### ISSUE THREAD

**Issue by sonia-ch** [elBjarnacho/KingOfTheCube#21]
The King of the Cube should be able to throw stuff such as rocks or bombs to the other players. Explosion effects are not included in this ticket.

**Comment by bjarnur** [comment]
Do you think it would be possible (and not too much work) to automate a character to semi-randomly move around and drop bombs? That way we could have an "AI King of the Cube" during the single-player 
demo next week 😃

**Comment by sonia-ch** [comment]
That's a really good idea! I could definitely work on that!

**Comment by sonia-ch** [comment]
The king can throw bombs/rocks (only a ball right now) when pressing the space key if it's controlled by the player. In AI-mode (there is a checkbox in kingController), he throws bombs randomly when he reaches the same side of the cube as the player.
- For future tickets: Improve the graphics of the "bombs/rocks" and add the explosion effects.
