### ISSUE TITLE
Update to version 1.5.0 of ARCore SDK

### ISSUE THREAD

**Issue by bjarnur** [elBjarnacho/KingOfTheCube#35]
There is a bug in the current version of the ARCore SDK for Unity, preventing Samsung Galaxy phones from being able to use the Instant Preview feature. The issue is solved in the upcoming release, so we should upgrade when possible. 

Probably the next version will be released sometime in the last days of August.

**Comment by bjarnur** [comment]
Have upgraded to the latest ARCore version, that fixes the previous bug. However new problems arise, and there is still no success with running Instant Preview on Samsung S7. 

Unclear whether the new issue is limited to Samsung phones, but apparently it only occurs when using the Augmented Image part of ARCore (which we are indeed using).  Bug has been reported here: https://github.com/google-ar/arcore-unity-sdk/issues/403

**Comment by LuisCRSousa** [comment]
Have a pixel 2 XL. This problem still persists
