### ISSUE TITLE
Making the AR cube 50x50x50

### ISSUE THREAD

**Issue by bjarnur** [elBjarnacho/KingOfTheCube#37]
The physical cube will have the dimensions 50x50x50. The AR cube should match these dimensions perfectly, so that when we scan our marker the virtual object should be wrapped around the physical object.

**Comment by NoNiMad** [comment]
Changed the scale from 0.1 to 0.16667 to get a 50x50x50cm cube. Tested with Instant Preview, works ok!
Change in commit: 6e46bdc419813d1ccc479479246bda4feb3d893c
