### ISSUE TITLE
Marker recognition

### ISSUE THREAD

**Issue by bjarnur** [elBjarnacho/KingOfTheCube#4]
Implement marker recognition, so that upon seeing our marker the application will produce a virtual cube. 

Once we have built our physical cube the application should add the relevant physical elements (such as ramps, balconies and stairs) to the physical cube.

**Comment by sonia-ch** [comment]
Marker recognition is already working. 
We are showing the desert model on top of a "King of the cube" 20x20cm marker.
Still need to adjust the virtual cube to the printed image. 
Next step: Try on a physical cube.

![whatsapp image 2018-09-11 at 17 59 10](https://user-images.githubusercontent.com/32477297/45372185-a500c300-b5ec-11e8-8e49-5ae1f68600d5.jpeg)

**Comment by bjarnur** [comment]
To keep this ticket from becoming too broad I suggest we close it now, since the goal of implementing 'Marker Recognition' has been accomplished. 

Further development is covered in other tickets, e.g. https://github.com/elBjarnacho/KingOfTheCube/issues/8

**Comment by NoNiMad** [comment]
It's really stable and we experimented a lot with AugmentedImages, it's indeed time to close this.
