### ISSUE TITLE
Correctly assembling virtual cube in AR

### ISSUE THREAD

**Issue by bjarnur** [elBjarnacho/KingOfTheCube#8]
Now that we have a working AR it's time to correctly assemble the virtual cube in AR. To begin with we can use a simple token printed on a piece of paper as a marker.

**Comment by bjarnur** [comment]
Tried struggling with this, but had a lot of problems with it. 

@NoNiMad - I will actually be free on Monday, maybe we could meet up then to try to solve this one together?

**Comment by bjarnur** [comment]
Actually started making some progress on this one! :) @NoNiMad will let you know what the status is before tomorrow!

**Comment by bjarnur** [comment]
@NoNiMad is this one ready to be closed? :)

**Comment by NoNiMad** [comment]
Depends on what you meant by "assembling" the cube, but the cube exists in AR and the player can move on platforms around it, jump on other platforms and climb ladders. Yeah, it's ok to close it ^^
